package dominio;

public enum TipoDeProducto {
	MOTHERBOARD, CPU, COOLER, GPU, RAM, ALMACENAMIENTO, FUENTE, GABINETE, MONITOR, TECLADO, MOUSE, MOUSEPAD, TELCADO, PARLANTES, UPS, ESTABILIZADOR, WEBCAM, AURICULARES, MICROFONO, CABLES, PERIFERICOS, OTRO;
}
